name: Clear gh-pages Branch

on:
  workflow_dispatch:

jobs:
  clear-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 1

      - name: Delete remote gh-pages branch
        run: |
          git push origin --delete gh-pages || echo "gh-pages branch doesn't exist"

      - name: Create new gh-pages branch
        run: |
          git switch --orphan gh-pages
          touch README.md
          git add README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -m "Reset gh-pages branch" || echo "Nothing to commit"

      - name: Push changes
        run: |
          git push origin gh-pages --force