name: Naptan Download and Parse Data

on:
  schedule:
    - cron: '0 8,20 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Maximise build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch Naptan
        run: |
          python -u naptan.py

      - name: Cleanup
        run: |
          find data/naptan -maxdepth 1 -type f -regex './naptan_[0-9]\{3\}\.json' -delete
          find data/naptan -maxdepth 1 -type f -regex './naptan_[0-9]\{3\}\.xml' -delete

      - name: Set commit message with timestamp
        run: echo "COMMIT_MSG=Update Naptan at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            target-folder: data/
            folder: data
            commit-message: ${{ env.COMMIT_MSG }}
            branch: gh-pages
            clean: false