name: Repository Stats

on:
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 1

      - name: List directories with file counts and total size
        run: |
          echo "=== Directory Summary Before Removing Empty Files ==="
          echo ""
          # For each directory (including root)
          # Print: total size + number of files + directory name
          find . -type d | while read dir; do
            count=$(find "$dir" -maxdepth 1 -type f | wc -l)
            size=$(du -sh "$dir" | awk '{print $1}')
            printf "%-50s Files: %-6s Size: %s\n" "$dir" "$count" "$size"
          done

      - name: Remove empty files
        run: |
          find . -type f \( -name "*.json" -o -name "*.geojson" \) -print0 | xargs -0 -P $(nproc) sh -c '
            for f do
              s=$(tr -d " \t\n\r" < "$f")

              if [ "$s" = "[]" ]; then
                rm "$f"
              fi

              if [ "$s" = "{}" ]; then
                rm "$f"
              fi
            done
          ' sh

      - name: List directories with file counts and total size
        run: |
          echo "=== Directory Summary After Removing Empty Files ==="
          echo ""
          # For each directory (including root)
          # Print: total size + number of files + directory name
          find . -type d | while read dir; do
            count=$(find "$dir" -maxdepth 1 -type f | wc -l)
            size=$(du -sh "$dir" | awk '{print $1}')
            printf "%-50s Files: %-6s Size: %s\n" "$dir" "$count" "$size"
          done

      - name: Find top 10 largest files in TNDS
        run: |
          echo ""
          echo "=== Top 10 Largest Files in TNDS/ ==="
          echo ""

          # Loop through each first-level directory inside ./data/tnds
          for dir in ./data/tnds/*/; do
            echo "=== Top 10 largest files in $dir ==="

            find "$dir" -type f -printf "%s %p\0" \
            | sort -z -nr \
            | head -z -n 10 \
            | awk -v RS='\0' '
              {
                # split only on the *first* space: size and rest is the path
                space = index($0, " ");
                size = substr($0, 1, space - 1);
                path = substr($0, space + 1);

                hum["GB"] = 1024^3; hum["MB"] = 1024^2; hum["KB"] = 1024;

                for (u in hum) {
                  if (size >= hum[u]) {
                    printf "%.2f %s  %s\n", size / hum[u], u, path;
                    next;
                  }
                }
                printf "%d B  %s\n", size, path;
              }
            '

            echo ""  # blank line between folders
          done