name: TNDS Download and Parse Data

on:
  schedule:
    - cron: '30 8,20 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Maximise build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch TNDS
        env:
          TNDS_FTP_USER: ${{ secrets.TNDS_FTP_USER }}
          TNDS_FTP_PWD: ${{ secrets.TNDS_FTP_PWD }}
        run: |
          python -u tnds.py

      - name: Cleanup
        run: |
          find data/tnds -maxdepth 1 -type f -name '*.zip' -delete
          find data/tnds -maxdepth 1 -type f -name 'servicereport.csv' -delete
          find data/tnds -maxdepth 1 -type f -name 'log.txt' -delete
          find data/tnds -maxdepth 2 -type f -name '*.xml' -delete
          find data/tnds -maxdepth 2 -type f -name '_*.json' -delete

      - name: Set commit message with timestamp
        run: echo "COMMIT_MSG=Update TNDS at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
            token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            target-folder: data
            folder: data
            commit-message: ${{ env.COMMIT_MSG }}
            branch: gh-pages
            clean: false